[BITS 16] ;; SET TO REAL MODE BY BIOS
[ORG 0x7C00] ;; SET TO BOOTLOADER ORIGIN

start:
    CLI ;;        S
    XOR AX, AX ;; E
    MOV DS, AX ;; T
    MOV ES, AX ;; U
    MOV SS, AX ;; P
    MOV SP, 0x7A00 ; THE
    STI ; STACK

    MOV [boot_drive], DL ;; SAVE BOOT DRIVE

read_retry:
    MOV AH, 0x42 ;; READ VIA LBA
    MOV DL, [boot_drive] ;; GET BOOT DRIVE
    MOV SI, dap ;; SET AS DISK ACCESS PACKET
    INT 0x13 ;; READ DISK
    JNC read_ok ;; READ IS OK

    XOR AH, AH ;; RESET DISK
    INT 0x13 ;; ALR THIS ONES OBVIOUS

    DEC BYTE [retries] ;; 3 RETRIES
    JNZ read_retry ;; RETRY IF RETRIES < 0

disk_error:
    HLT ;; HALT
    JMP disk_error ;; YOU SHALL NOT PASS

read_ok:
    JMP 0x0000:0x7E00 ;; READ IS OK CLEARED FOR HYPER JUMP

dap:
    DB 0x10 ;; SIZE
    DB 0 ;; RESERVED FOR RESERVATION (ON THE DISNEY MOBILE APP)
    DW 4 ;; NUMBER OF SECTORS TO READ (4 SECTORS THATS ALOT OF PAGES!)
    DW 0x7E00 ;; OFFSET!!
    DW 0x0000 ;; SEGMENT!
    DQ 1 ;; 64 BIT LBA (0 DOES NOT WORK AND I DONT WANT TO LOOK UP THE ANSWER CUZ ITS GOING TO TAKE UP HALF MY LIFETIME(USUALY))

boot_drive DB 0 ;; OBVIOUS
retries    DB 3 ;; SAME AS ABOVE

TIMES 510-($-$$) DB 0 ;; PADDING FOR WHEN YOU FALL AND NOT USE THOSE 512 BYTES
DW 0xAA55 ;; BOOT SIGNIATURE (WEIRD NAME HUH?)
