[BITS 16] ;; REAL MODE!!!
;; REMOVE FOR ELF'S [ORG 0x7E00] ;; ROOMMATES WITH BOOT.ASM (0x7C00)

EXTERN gdt_descriptor ;; DEFINE EXERNAL
EXTERN pm_entry ;;       SYMBOLS

CODE_SEG EQU 0x08 ;; CODE SEG!

main:
    CLI ;; NO MORE INTERUPS CPU!!
    XOR AX, AX ;; AX = 0
    MOV DS, AX ;; DS = 0 0x0000:
    MOV ES, AX ;; ES = 0 0x0000
    MOV AX, 0x0003 ;; SET VGA TO TEXT MODE
    INT 0x10 ;; INTERUPT ME
    
    LGDT [gdt_descriptor] ;; LOAD THIS GDT

    MOV EAX, CR0 ;; EAX GETS CR0 CR0
    OR EAX, 1 ;; SET PE BIT TO CR0
    MOV CR0, EAX ;; SAVE TO CR0
    JMP CODE_SEG:pm_entry ;; JUMP TO FUNC

hang_rm:
    HLT ;; HALT
    JMP hang_rm ;; YOU SHALL NOT PASS

