GLOBAL pm_entry ;; GLOBAL PM_ENTRY
EXTERN bmain ;; EXTERNAL C!!

DATA_SEG: EQU 0x10 ;; DATA SEG!!

[BITS 32] ;; YESS PROTECTED MODE!!
pm_entry:
    MOV AX, DATA_SEG ;; AX = DATA_SEG FOR SETTING SEGMENTS
    MOV DS, AX ;; DS = DATA_SEG
    MOV ES, AX ;; ES = DATA_SEG
    MOV GS, AX ;; GS = DATA_SEG
    MOV FS, AX ;; FS = DATA_SEG
    MOV SS, AX ;; SS = DATA_SEG
    MOV ESP, 0x9FC00 ;; STACK POINTER TO 0x9FC00
    AND ESP, 0xFFFFFFF0 ;; AND? WHAT
    CALL bmain ;; CALL KMAIN FUNC (IN BOOT.C)
    
hang_pm:
    CLI ;; NO INTERUPTS
    HLT ;; HALT
    JMP hang_pm ;; STOP